# Generated by Django 5.2.8 on 2025-11-17 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_employeedata_created_at_employeedata_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeedata',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='employeedata',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
